apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
  namespace: kube-system
  labels:
    type: alert-rules
data:
  alerts.yaml: |
    groups:
    - name: example
      rules:
      - alert: HighErrorRate
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latenc
